# Generated by Django 3.2.6 on 2022-10-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210914_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysreq',
            name='max',
        ),
        migrations.RemoveField(
            model_name='sysreq',
            name='min',
        ),
        migrations.RemoveField(
            model_name='product',
            name='on_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='system_requirements',
        ),
        migrations.RemoveField(
            model_name='product',
            name='users_wishlist',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.franchise'),
        ),
        migrations.AlterField(
            model_name='product',
            name='platform',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Minsysreq',
        ),
        migrations.DeleteModel(
            name='Recsysreq',
        ),
        migrations.DeleteModel(
            name='sysreq',
        ),
    ]
