# Generated by Django 3.2.6 on 2021-09-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userbase_last_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userbase',
            managers=[
            ],
        ),
    ]
